spring:
  application:
    name: stocks
  r2dbc:
    url: r2dbc:mysql://${DB_URL}/assignment
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      initial-size: 1
      max-size: 3
      max-idle-time: 30m
logging:
  level:
    org.ktb.stocks: debug
api:
  key:
    header: 'x-api-key'
    secrets:
    - 'c18aa07f-f005-4c2f-b6db-dff8294e6b5e'
    - 'hello'